import { Injectable } from '@angular/core';
import { Product } from '../model/product';

@Injectable({
  providedIn: 'root'
})
export class ProductService {
list: Product[] = 
[{"id":1,"catId":2,"name":"hgadie0","description":"amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim","image":`../../assets/img/ca188x204.jpg`,"price":8528,"stock":17,"featured":true,"active":true},
{"id":2,"catId":2,"name":"scolcutt1","description":"mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi","image":`../../assets/img/ca188x204.jpg`,"price":8088,"stock":25,"featured":true,"active":false},
{"id":3,"catId":1,"name":"pmereweather2","description":"sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices","image":"../../assets/img/kalium188x204.jpg","price":4292,"stock":25,"featured":true,"active":true},
{"id":4,"catId":1,"name":"sgilluley3","description":"eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique","image":"../../assets/img/kalium188x204.jpg","price":6038,"stock":13,"featured":true,"active":false},
{"id":5,"catId":1,"name":"amannering4","description":"id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum","image":"../../assets/img/krom188x204.jpg","price":9828,"stock":17,"featured":false,"active":false},
{"id":6,"catId":2,"name":"jmaccrea5","description":"odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien","image":`../../assets/img/ca188x204.jpg`,"price":9887,"stock":29,"featured":false,"active":true},
{"id":7,"catId":2,"name":"kcrandon6","description":"ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet","image":`../../assets/img/ca188x204.jpg`,"price":1375,"stock":25,"featured":true,"active":true},
{"id":8,"catId":1,"name":"colennachain7","description":"at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci","image":`../../assets/img/ca188x204.jpg`,"price":5882,"stock":25,"featured":false,"active":true},
{"id":9,"catId":1,"name":"bwhordley8","description":"nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse","image":"../../assets/img/kalium188x204.jpg","price":9225,"stock":11,"featured":true,"active":false},
{"id":10,"catId":1,"name":"dboord9","description":"augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl","image":"../../assets/img/mg188x204.png","price":4155,"stock":29,"featured":false,"active":true},
{"id":11,"catId":2,"name":"ktalea","description":"mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse","image":"../../assets/img/mg188x204.png","price":4178,"stock":13,"featured":true,"active":true},
{"id":12,"catId":1,"name":"nmaddinb","description":"et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat","image":"../../assets/img/krom188x204.jpg","price":4192,"stock":31,"featured":false,"active":true},
{"id":13,"catId":2,"name":"shornungc","description":"fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst","image":"../../assets/img/kalium188x204.jpg","price":8251,"stock":5,"featured":false,"active":false},
{"id":14,"catId":2,"name":"ftrussloved","description":"tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque","image":"../../assets/img/mg188x204.png","price":6402,"stock":11,"featured":true,"active":true},
{"id":15,"catId":2,"name":"cthreshere","description":"rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet","image":`../../assets/img/ca188x204.jpg`,"price":5815,"stock":16,"featured":true,"active":false},
{"id":16,"catId":1,"name":"hsweetmanf","description":"dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien","image":"../../assets/img/krom188x204.jpg","price":1433,"stock":13,"featured":false,"active":false},
{"id":17,"catId":2,"name":"astrottong","description":"diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non","image":"../../assets/img/kalium188x204.jpg","price":2683,"stock":29,"featured":false,"active":true},
{"id":18,"catId":2,"name":"srippenh","description":"pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis","image":"../../assets/img/mg188x204.png","price":5655,"stock":23,"featured":false,"active":false},
{"id":19,"catId":2,"name":"cmoxtedi","description":"ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at","image":`../../assets/img/ca188x204.jpg`,"price":7165,"stock":29,"featured":false,"active":true},
{"id":20,"catId":1,"name":"smcconigalj","description":"at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla","image":`../../assets/img/ca188x204.jpg`,"price":1672,"stock":31,"featured":true,"active":false},
{"id":21,"catId":2,"name":"lpilkintonk","description":"magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in","image":"../../assets/img/mg188x204.png","price":561,"stock":9,"featured":true,"active":false},
{"id":22,"catId":2,"name":"avezeyl","description":"imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor","image":"../../assets/img/krom188x204.jpg","price":882,"stock":28,"featured":false,"active":false},
{"id":23,"catId":2,"name":"gbedenm","description":"magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque","image":"../../assets/img/kalium188x204.jpg","price":3141,"stock":31,"featured":false,"active":false},
{"id":24,"catId":2,"name":"asaltern","description":"varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci","image":"../../assets/img/kalium188x204.jpg","price":1659,"stock":17,"featured":false,"active":true},
{"id":25,"catId":2,"name":"abertino","description":"justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id","image":"../../assets/img/mg188x204.png","price":2354,"stock":28,"featured":true,"active":true},
{"id":26,"catId":1,"name":"gartonp","description":"congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris","image":"../../assets/img/kalium188x204.jpg","price":4867,"stock":31,"featured":true,"active":true},
{"id":27,"catId":2,"name":"mchallinorq","description":"nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet","image":"../../assets/img/krom188x204.jpg","price":4654,"stock":25,"featured":false,"active":false},
{"id":28,"catId":2,"name":"dsneydr","description":"justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra","image":"../../assets/img/kalium188x204.jpg","price":4069,"stock":29,"featured":false,"active":true},
{"id":29,"catId":2,"name":"kbeevorss","description":"aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac","image":`../../assets/img/ca188x204.jpg`,"price":4375,"stock":19,"featured":false,"active":false},
{"id":30,"catId":2,"name":"agladebeckt","description":"magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien","image":"../../assets/img/krom188x204.jpg","price":4294,"stock":29,"featured":true,"active":false},
{"id":31,"catId":1,"name":"clanhamu","description":"neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan","image":"../../assets/img/mg188x204.png","price":8216,"stock":29,"featured":true,"active":true},
{"id":32,"catId":1,"name":"dduxfieldv","description":"amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at","image":"../../assets/img/mg188x204.png","price":1942,"stock":17,"featured":false,"active":false},
{"id":33,"catId":2,"name":"mcroslandw","description":"justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat","image":"../../assets/img/krom188x204.jpg","price":7876,"stock":25,"featured":true,"active":false},
{"id":34,"catId":1,"name":"rbartholomausx","description":"vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum","image":"../../assets/img/krom188x204.jpg","price":1718,"stock":29,"featured":false,"active":true},
{"id":35,"catId":1,"name":"cmettrickey","description":"nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris","image":`../../assets/img/ca188x204.jpg`,"price":6388,"stock":16,"featured":true,"active":false},
{"id":36,"catId":2,"name":"igravellz","description":"massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo","image":"../../assets/img/kalium188x204.jpg","price":8954,"stock":16,"featured":false,"active":false},
{"id":37,"catId":1,"name":"elerway10","description":"nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante","image":"../../assets/img/krom188x204.jpg","price":7096,"stock":9,"featured":false,"active":false},
{"id":38,"catId":2,"name":"ileatham11","description":"pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis","image":"../../assets/img/krom188x204.jpg","price":3263,"stock":9,"featured":true,"active":false},
{"id":39,"catId":1,"name":"rlynnett12","description":"duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel","image":"../../assets/img/mg188x204.png","price":9865,"stock":31,"featured":false,"active":true},
{"id":40,"catId":1,"name":"imixture13","description":"vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit","image":"../../assets/img/krom188x204.jpg","price":5709,"stock":9,"featured":false,"active":true},
{"id":41,"catId":1,"name":"fgeldard14","description":"at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices","image":"../../assets/img/krom188x204.jpg","price":1241,"stock":11,"featured":false,"active":false},
{"id":42,"catId":1,"name":"mrasher15","description":"elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis","image":"../../assets/img/kalium188x204.jpg","price":9244,"stock":25,"featured":true,"active":false},
{"id":43,"catId":1,"name":"wzaniolo16","description":"accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio","image":"../../assets/img/krom188x204.jpg","price":7855,"stock":23,"featured":false,"active":true},
{"id":44,"catId":2,"name":"stipper17","description":"posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam","image":"../../assets/img/kalium188x204.jpg","price":5730,"stock":29,"featured":false,"active":false},
{"id":45,"catId":1,"name":"trigts18","description":"nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel","image":`../../assets/img/ca188x204.jpg`,"price":4536,"stock":25,"featured":false,"active":true},
{"id":46,"catId":2,"name":"jrobins19","description":"vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in","image":`../../assets/img/ca188x204.jpg`,"price":8727,"stock":25,"featured":false,"active":true},
{"id":47,"catId":2,"name":"dbennoe1a","description":"nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur","image":"../../assets/img/krom188x204.jpg","price":2632,"stock":25,"featured":false,"active":true},
{"id":48,"catId":1,"name":"lrudgard1b","description":"eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer","image":`../../assets/img/ca188x204.jpg`,"price":1912,"stock":9,"featured":false,"active":true},
{"id":49,"catId":1,"name":"ngott1c","description":"tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor","image":"../../assets/img/mg188x204.png","price":4460,"stock":13,"featured":false,"active":true},
{"id":50,"catId":1,"name":"rmoyne1d","description":"hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi","image":"../../assets/img/mg188x204.png","price":7774,"stock":11,"featured":true,"active":false}]

  constructor() { }
}
